name:                MarvelChampions

dependencies:
- base >= 4.7 && < 5
- relude
- MonadRandom
- mtl
- text
- exceptions
- unordered-containers
- lens

default-extensions:
- NoImplicitPrelude
- LambdaCase
- DerivingStrategies
- GeneralizedNewtypeDeriving
- FlexibleContexts
- DeriveGeneric
- TypeOperators
- OverloadedStrings
- ImportQualifiedPost
- BlockArguments
- MultiParamTypeClasses
- FunctionalDependencies
- TupleSections
- KindSignatures
- TypeFamilies
- TypeApplications
- ScopedTypeVariables
- RankNTypes
- RecordWildCards

library:
  source-dirs: library
  dependencies:
  - uuid
  - vector

executables:
  MarvelChampions-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MarvelChampions

tests:
  MarvelChampions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MarvelChampions
