name:                MarvelChampions

dependencies:
- base >= 4.7 && < 5
- relude

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: library

executables:
  MarvelChampions-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MarvelChampions

tests:
  MarvelChampions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MarvelChampions
