---
require-stack-version: ">= 2.3.1"
concurrent-tests: false
system-ghc: true
install-ghc: false
resolver: nightly-2023-06-27
compiler: ghc-9.6.2

ghc-options:
  "$locals":
    -fhide-source-paths
    -Weverything
    -Wno-missing-exported-signatures
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-import-lists
    -Wno-missing-export-lists
    -Wno-incomplete-uni-patterns
    -Wno-partial-fields
    -Wno-implicit-prelude
    -Wno-deriving-typeable
    -Wno-missing-kind-signatures
    -fignore-optim-changes
    -Wno-missing-safe-haskell-mode
    -Wno-prepositive-qualified-module
    -fwrite-ide-info
    -hiedir=.hie

packages:
- marvel-core
- marvel-api
- cards-discover

allow-newer: true

extra-deps:
- esqueleto-3.5.10.0
- yesod-1.6.2.1
- yesod-persistent-1.6.0.8
- persistent-2.14.5.1
- persistent-postgresql-2.13.5.2
- yesod-websockets-0.3.0.3
- yesod-core-1.6.24.2
- github: jmazon/clientsession
  commit: 1221230770feff60f77ff676d52fc464cb77b2d9
