name: marvel-core

dependencies:
- base >= 4.7 && < 5
- relude
- MonadRandom
- text
- exceptions
- lens
- extra

default-extensions:
- BlockArguments
- DefaultSignatures
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- ViewPatterns

library:
  source-dirs: library
  dependencies:
  - uuid
  - vector
  - template-haskell
  - unordered-containers
  - aeson
  - aeson-diff
  - aeson-casing
  - random-shuffle

tests:
  MarvelChampions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - marvel-core
