name: marvel-core

dependencies:
- base >= 4.7 && < 5
- relude
- MonadRandom
- mtl
- text
- exceptions
- lens
- extra

default-extensions:
- ExistentialQuantification
- NoImplicitPrelude
- LambdaCase
- DerivingStrategies
- GeneralizedNewtypeDeriving
- FlexibleContexts
- DeriveGeneric
- TypeOperators
- OverloadedStrings
- ImportQualifiedPost
- BlockArguments
- MultiParamTypeClasses
- FunctionalDependencies
- TupleSections
- KindSignatures
- TypeFamilies
- TypeApplications
- ScopedTypeVariables
- RankNTypes
- RecordWildCards
- DeriveAnyClass
- StandaloneDeriving
- FlexibleInstances
- UndecidableInstances
- ViewPatterns

library:
  source-dirs: library
  dependencies:
  - uuid
  - vector
  - template-haskell
  - unordered-containers
  - aeson
  - aeson-diff
  - aeson-casing
  - random-shuffle

tests:
  MarvelChampions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - marvel-core
